# Use a Node base image (Alpine version for smaller footprint)
FROM node:22

# Create and set the working directory
WORKDIR /app/frontend

RUN npm install -g @angular/cli

# Copy only package.json and package-lock.json from the frontend folder first
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the entire frontend folder contents into the working directory
COPY ./ /app

# Expose Angular's default port
EXPOSE 3000

# Run the Angular app
CMD ["npm", "start"]